language: java

sudo: false
dist: trusty

os:
  - linux

jdk:
  - oraclejdk8
  - openjdk11

before_script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}

script:
  - java -version

after_script:
  - ls ${JAVA_HOME}
  - cat "${JAVA_HOME}/release"

# configure caching (https://docs.travis-ci.com/user/languages/java/#Caching)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# format from https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features
cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper
