language: java

sudo: false
dist: trusty

os:
  - linux

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uharaqo"
    token:
      secure: "ZuP6WjO9fg49GCmTWuIMcBB0/EkDwreQdUpGgXfF47hMlLKU4dEUOTA7Evw0eJZCwvQ8l1c5NW3tkL8SPE5uxvgmKN+0FR8Z8+rMEBQc92zHUcsoKyRO1fs7H2PWcRufJ6IlU9pJlrHZYTrHU3owYCsSp+QzmqxTniRilpUxgjqK0xEDaxzqGG+ZX/mdADi3rE79CJ15BHKiClL++3BbfTDnWPlHowsNstNncoHGJbR1AuUhgSwsxuqxs6Q/Or+GyYiNsnp5qp2+ssn7vSNm3OCKRQ7UXgfOrcn05BeQN8xLq2Ek06LT1MIM0oVYSoH8tgqGkWcMzz7fC6L61TGebt+/7I/EDZ4tthwy3tZtFGq/pZyaEsqnlZR3udpzdFisfr6LgHyE6vgz1Ia1U+I67+0P5z5cNbvTC64cQr8DnRn29/lvqWVi+mXVpnYSBZlLVf4dexJGASnovZQvczyowpcE86Z99HZeTxvEXVJmoV0Y//aNC70pra0puwFw5CxUxC2yGl3avyQgDQIB0ufWROdNVaeWJY0kn3G+uML9sNkzcHxEF1GD8YYxlddbRlY8VHUS7BiCV1NUvsZBIWcym8TMVfw+MWMFZmUtsSs/cKT4Rrj8rSBS6yAqr9HqEbsu2yzg7XJx8AbXWa+eT8AbidAsho2OC+09oRF1N2cl7lw="

before_script:
  - java -version
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew clean build
  - ./gradlew coverageReport
  - sonar-scanner

after_script:
  - ls ${JAVA_HOME}
  - cat "${JAVA_HOME}/release"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - ./gradlew dokkaJar javadocJar sourcesJar generatePomFileForBintrayPublication

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  dry-run: false
  on:
    branch: master

# configure caching (https://docs.travis-ci.com/user/languages/java/#Caching)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# format from https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features
cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper
